# Nome do workflow
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - azure-main # Aciona o workflow quando há push na branch principal de deploy
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - azure-main # Também é executado para PRs abertos ou atualizados na mesma branch

jobs:
  build_and_deploy_job:
    # Executa o job apenas quando for push ou PR ativo (não fechado)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    # Variáveis de ambiente usadas na aplicação durante o build
    env:
      NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
      NEXT_PUBLIC_BACKEND_AUTH_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_AUTH_URL }}
      NEXT_PUBLIC_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_SECRET_KEY }}

    steps:
      # Faz checkout do código no runner
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Etapa principal de build e deploy
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MOSS_04D1C2803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Token usado para integração com PRs
          action: "upload"

          ###### Configurações do repositório / build ######
          app_location: "/" # Caminho do código-fonte da aplicação
          api_location: "" # Caminho da API (opcional)
          output_location: "" # Diretório de saída após o build (opcional)
          ###### Fim das configurações ######

  close_pull_request_job:
    # Executa apenas quando o PR é fechado
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MOSS_04D1C2803 }}
          action: "close"

